[package]
name = "packgs"
version = "0.1.0"
edition = "2021"

[dependencies]
alpm = "3.0.5"
alpm-utils = "3.0.2"
color-eyre = { version = "0.6.3", default-features = false, features = ["track-caller"] }
crossterm = "0.27.0"
ratatui = "0.26.3"
time = "0.3.36"
